/**
 * @description Post-codegen workarounds, run after `nitrogen` by `bun run codegen`.
 * Originally generated by create-nitro-module and extended for this package:
 *
 * - Android: removes the 'margelo/nitro/' prefix from '<ModuleName>OnLoad.cpp' and rewrites
 *   the view manager imports so the custom package name (`com.nitroshimmertext`) resolves.
 * - iOS: renames the numeric FontWeight enum cases (`100` → `_100`), which are not valid
 *   Swift identifiers.
 * - Shared C++: fills `Props::rawProps` in the generated props constructor so base View props
 *   reach Android on React Native >= 0.87 (https://github.com/margelo/nitro/issues/1656).
 *
 * All replacements are idempotent, so running the script twice is safe.
 */
const path = require('node:path');
const { readdir, readFile, writeFile } = require('node:fs/promises');

const GENERATED = path.join(process.cwd(), 'nitrogen/generated');
const VIEW_MANAGER_DIR = path.join(
  GENERATED,
  'android/kotlin/com/margelo/nitro/nitroshimmertext/views',
);

const replaceInFile = async (file, pattern, replacement) => {
  const content = await readFile(file, { encoding: 'utf8' });
  await writeFile(file, content.replace(pattern, replacement));
};

const iosWorkaround = async () => {
  await replaceInFile(
    path.join(GENERATED, 'ios/swift/FontWeight.swift'),
    /\.([1-9]00)\b/g,
    '._$1',
  );
  await replaceInFile(
    path.join(GENERATED, 'shared/c++/FontWeight.hpp'),
    /SWIFT_NAME\(([1-9]00)\)/g,
    'SWIFT_NAME(_$1)',
  );
};

const androidWorkaround = async () => {
  const viewManagerFiles = (await readdir(VIEW_MANAGER_DIR)).filter((file) =>
    file.endsWith('Manager.kt'),
  );
  await Promise.all(
    viewManagerFiles.map((file) =>
      replaceInFile(
        path.join(VIEW_MANAGER_DIR, file),
        /com\.margelo\.nitro\.nitroshimmertext\.\*/g,
        'com.nitroshimmertext.*',
      ),
    ),
  );
  await replaceInFile(
    path.join(GENERATED, 'android/NitroShimmerTextOnLoad.cpp'),
    /margelo\/nitro\//g,
    '',
  );
};

// Nitro's ViewComponentDescriptor overrides cloneProps without calling
// initializeDynamicProps. Since React Native 0.87 the Props constructor no longer
// fills `rawProps`, which Android serializes to Java to apply base View props
// (testID, style, accessibility...). Fill it from the generated constructor so
// Nitro's own props stay filtered out. Remove once upstream ships a fix:
// https://github.com/margelo/nitro/issues/1656
const RAW_PROPS_MARKER = 'margelo/nitro/issues/1656';
const rawPropsWorkaround = async () => {
  const file = path.join(
    GENERATED,
    'shared/c++/views/HybridNitroShimmerTextComponent.cpp',
  );
  let content = await readFile(file, { encoding: 'utf8' });
  if (content.includes(RAW_PROPS_MARKER)) return;

  const include = '#include <NitroModules/ReactProp.hpp>\n';
  const propsConstructor =
    /(HybridNitroShimmerTextProps::HybridNitroShimmerTextProps\(const react::PropsParserContext& context,[\s\S]*?\)\)) \{ \}/;
  if (!content.includes(include) || !propsConstructor.test(content)) {
    throw new Error(
      `rawProps workaround: unexpected codegen output in ${file}`,
    );
  }
  content = content
    .replace(
      include,
      `${include}\n#ifdef ANDROID\n#include <cxxreact/ReactNativeVersion.h>\n#endif\n`,
    )
    .replace(
      propsConstructor,
      `$1 {
#if defined(RN_SERIALIZABLE_STATE) && (REACT_NATIVE_VERSION_MAJOR > 0 || REACT_NATIVE_VERSION_MINOR >= 87)
    // Workaround for https://github.com/margelo/nitro/issues/1656 (added by post-script.js)
    initializeDynamicProps(sourceProps, rawProps, filterObjectKeys);
#endif
  }`,
    );
  await writeFile(file, content);
};

Promise.all([androidWorkaround(), iosWorkaround(), rawPropsWorkaround()]).catch(
  (error) => {
    console.error('post-script failed:', error);
    process.exit(1);
  },
);
