/**
 * @description Post-codegen workarounds, run after `nitrogen` by `bun run codegen`.
 * Originally generated by create-nitro-module and extended for this package:
 *
 * - Android: removes the 'margelo/nitro/' prefix from '<ModuleName>OnLoad.cpp' and rewrites
 *   the view manager imports so the custom package name (`com.nitroshimmertext`) resolves.
 * - iOS: renames the numeric FontWeight enum cases (`100` → `_100`), which are not valid
 *   Swift identifiers.
 *
 * All replacements are idempotent, so running the script twice is safe.
 */
const path = require('node:path');
const { readdir, readFile, writeFile } = require('node:fs/promises');

const GENERATED = path.join(process.cwd(), 'nitrogen/generated');
const VIEW_MANAGER_DIR = path.join(
  GENERATED,
  'android/kotlin/com/margelo/nitro/nitroshimmertext/views'
);

const replaceInFile = async (file, pattern, replacement) => {
  const content = await readFile(file, { encoding: 'utf8' });
  await writeFile(file, content.replace(pattern, replacement));
};

const iosWorkaround = async () => {
  await replaceInFile(
    path.join(GENERATED, 'ios/swift/FontWeight.swift'),
    /\.([1-9]00)\b/g,
    '._$1'
  );
  await replaceInFile(
    path.join(GENERATED, 'shared/c++/FontWeight.hpp'),
    /SWIFT_NAME\(([1-9]00)\)/g,
    'SWIFT_NAME(_$1)'
  );
};

const androidWorkaround = async () => {
  const viewManagerFiles = (await readdir(VIEW_MANAGER_DIR)).filter((file) =>
    file.endsWith('Manager.kt')
  );
  await Promise.all(
    viewManagerFiles.map((file) =>
      replaceInFile(
        path.join(VIEW_MANAGER_DIR, file),
        /com\.margelo\.nitro\.nitroshimmertext\.\*/g,
        'com.nitroshimmertext.*'
      )
    )
  );
  await replaceInFile(
    path.join(GENERATED, 'android/NitroShimmerTextOnLoad.cpp'),
    /margelo\/nitro\//g,
    ''
  );
};

Promise.all([androidWorkaround(), iosWorkaround()]).catch((error) => {
  console.error('post-script failed:', error);
  process.exit(1);
});
